[package]
name = "easy-imgui-filechooser"
version = "0.1.0"
edition = "2021"

[dependencies]
easy-imgui = { version = "0.6.0", path = "../easy-imgui" }
image = "0.25"
glob = "0.3"
time = { version = "0.3", features = ["macros", "formatting"] }
bitflags = "2"
bytesize = "1"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.57", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
easy-imgui-window = { version = "0.6.0", path = "../easy-imgui-window" }

